# Generated by Django 5.1.1 on 2025-03-27 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('capacidad', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCorporativa',
            fields=[
                ('id_compra_corporativa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('numeroDocumento', models.CharField(default='', max_length=15)),
                ('tipoDocumento', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('stockDisponible', models.PositiveIntegerField(default=1)),
                ('stockReservado', models.PositiveIntegerField(default=1)),
                ('ultimaActualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id_nota_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('totalBruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalNeto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='Completado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(default='', max_length=11, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Administrador', 'Administrador')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='productos/', verbose_name='producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_compraCorporativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compracorporativa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MixCarga',
            fields=[
                ('id_mix_carga', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('cantidad', models.PositiveIntegerField()),
                ('id_distribuidor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.distribuidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionVentas',
            fields=[
                ('id_liquidacion_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('total_liquidado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadVentas', models.IntegerField(default=0)),
                ('idMixCarga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDistribucion',
            fields=[
                ('id_liquidacion_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('total_distribuido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.distribuidor')),
                ('idMixCarga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga')),
            ],
        ),
        migrations.CreateModel(
            name='LibroVentas',
            fields=[
                ('id_libro_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('total_Facturado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_Neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idMixCarga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(default='', max_length=50)),
                ('fechaEmision', models.DateTimeField(auto_now_add=True)),
                ('totalBruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_Neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('tipoDocumento', models.CharField(default='Factura', max_length=50)),
                ('razon_social', models.CharField(default='', max_length=200)),
                ('direccion_fiscal', models.TextField(default='')),
                ('rut', models.CharField(default='', max_length=11)),
                ('idMixCarga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga')),
                ('idNotaVenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.notaventa')),
                ('idPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.persona'),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('stockFinal', models.PositiveIntegerField(default=0)),
                ('idAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.almacen')),
                ('idDetalleCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.detallecompra')),
                ('idInventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.inventario')),
                ('idMixCarga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_entrega', models.TextField()),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.distribuidor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_ruta',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.ruta'),
        ),
    ]
