# Generated by Django 5.1.1 on 2025-03-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_persona_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='distribuidor',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='puntos_entrega',
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ruta',
            name='zona',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
