# Generated by Django 5.1.1 on 2025-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_ruta_distribuidor_remove_ruta_puntos_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id_ruta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='zona',
            field=models.CharField(default='', max_length=4),
        ),
    ]
