# Generated by Django 5.1.1 on 2025-03-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_ruta_id_ruta_alter_ruta_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
