# Generated by Django 5.1.1 on 2025-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_persona_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='diVerifica',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
