# Generated by Django 5.1.1 on 2025-04-01 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_detallefactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
