# Generated by Django 5.1.1 on 2025-04-01 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_kardex_fecha_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracorporativa',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
