# Generated by Django 5.1.1 on 2025-04-01 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_pedido_fecha_entrega_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroventas',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
