# Generated by Django 5.1.1 on 2025-04-01 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_liquidacionventas_fecha_liquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidaciondistribucion',
            name='fecha_liquidacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
