# Generated by Django 5.1.1 on 2025-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_factura_fechaemision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechaEmision',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
