# Generated by Django 5.1.1 on 2025-04-01 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_alter_factura_fechaemision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaventa',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
