# Generated by Django 5.1.1 on 2025-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_notaventa_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
