# Generated by Django 5.1.1 on 2025-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_persona_last_login_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BaJei4tstC4WFaXw4EWhkj$Ji7b14b9b2PW63PKnM1RR4gjg6lyL/m0VNi3oSU+wts=', max_length=128),
        ),
    ]
