# Generated by Django 5.1.1 on 2025-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$kLLZj84pSV9KMB4rcUwH7P$+opgkcAYuvGwSOtPCAuf8qULtdJzFdeg7HFO9ZMDg6k=', max_length=128),
        ),
    ]
