# Generated by Django 5.1.1 on 2025-05-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_alter_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='idNotaVenta',
        ),
        migrations.RemoveField(
            model_name='libroventas',
            name='idMixCarga',
        ),
        migrations.AddField(
            model_name='libroventas',
            name='id_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.factura'),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='id_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idMixCarga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.mixcarga'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jzFnSbI3bsFL1Xt0N0pBOq$NtkdVowWo+INWEPZHX49RhbRYMUp9mguZozTVdAFUuE=', max_length=128),
        ),
    ]
