# Generated by Django 5.1.1 on 2025-05-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_remove_factura_idnotaventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaventa',
            name='id_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.factura'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$vk0HIcRNy4ZsGLBuuLPP0q$qCOGgWmfbQWCoyEY+xJfZdeCHfsFhDYHTXDkp6c1iHE=', max_length=128),
        ),
    ]
