# Generated by Django 5.1.1 on 2025-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_alter_notaventa_id_factura_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8ApQcfOkBHsu5za9J822wN$M+yxFzvVMvYKeIQ6WmdQ4JuZAYXnB3lPcup71mKrU3A=', max_length=128),
        ),
    ]
