# Generated by Django 5.1.1 on 2025-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Y3L542bL9p2AJBGPmixvLi$MOLBP/Hv7OzhNv53yeUKOXegodrYsDVrM4Ajefmsud8=', max_length=128),
        ),
    ]
