# Generated by Django 5.1.1 on 2025-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YCr3NMf5q0LwPj9hvbZlgV$S14Kj/yJvuAO0KvhEvVAWFI4KPTdcgDcapwHl5K7Z/E=', max_length=128),
        ),
    ]
