# Generated by Django 5.1.1 on 2025-05-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$wdZcektOGD8qR4n8ERFLMk$RTFefmC6vi7WfbqewdYrAMo0kDZdAyP+Ne7nHE6y7Ow=', max_length=128),
        ),
    ]
