# Generated by Django 5.1.1 on 2025-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_detallefactura_idproducto_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$uQ4IzN3z2j7zPCoADhJ0bc$DRVpBDjs0b/VkE8CFHWk55AincweNhNJgfJN0GhzQPc=', max_length=128),
        ),
    ]
