# Generated by Django 5.1.1 on 2025-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0030_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$M9IAJhWhjCwo3XIQivTup4$GJM0StUBAA2wTXzS1tXFLhB+qwI39wPdXpwlaTpQXAg=', max_length=128),
        ),
    ]
