# Generated by Django 5.1.1 on 2025-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$aTWgYd30uL9Qcrmg0WODoM$kalXbAO+NF+zzPjpx2+7Gkh62UBvdd77V6+0b9w1SH4=', max_length=128),
        ),
    ]
