# Generated by Django 5.1.1 on 2025-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Hx0chvnLIEuAvWdWSCTVHH$XyKHkLfP3MsrmWdcuLvDdHiPSIwQevVpgzV0te3V8KM=', max_length=128),
        ),
    ]
