# Generated by Django 5.1.1 on 2025-05-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0033_alter_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='idMixCarga',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_mix_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.mixcarga'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xhUe8n2COlN7Nb8CO8zfqU$fcyV1dLBDclEzzZFYdBfwBLkYLj9qo7Lv9GcrIY5KAA=', max_length=128),
        ),
    ]
