# Generated by Django 5.1.1 on 2025-05-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0034_remove_factura_idmixcarga_pedido_id_mix_carga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_mix_carga',
        ),
        migrations.AddField(
            model_name='factura',
            name='idMixCarga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.mixcarga'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xAgLWjOPoNj30cLKnt1XZe$JaCY2j1oSyEXQtxD8NNNd94JQ/MJ4oeDB03pk1DU9Ek=', max_length=128),
        ),
    ]
