# Generated by Django 5.1.1 on 2025-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0036_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$o67erbXAsqFS10tn4XMgwW$brmMLEIHEvSNRQv5BLcaDnqIUCLX292OjDi0k7p4sew=', max_length=128),
        ),
    ]
