# Generated by Django 5.1.1 on 2025-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0037_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$dzpKLNt6aK8SHZS3PZtH57$NnnxFkoERIxU8P6V/NjjHI+nN7s/v1gkM6fhAd0dyEc=', max_length=128),
        ),
    ]
