# Generated by Django 5.1.1 on 2025-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0038_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Xa3TkSoJv4veGzh0XY8Keb$3vWc9XSCHQIMOT4BgRzZEe6ytpqSeTytIjBeQv7i/BU=', max_length=128),
        ),
    ]
