# Generated by Django 5.1.1 on 2025-05-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0039_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.almacen'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$he7x5w4CHQyKnKWhB2un0j$PaeAilbCs3QC2u3r/h1LZMnev634AsxVa7Vvl9x2lBA=', max_length=128),
        ),
    ]
