# Generated by Django 5.1.1 on 2025-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0040_producto_id_almacen_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7OAN6poQZ0iDOtwOAriXaF$Oi75L/AD5xIGC3OKkBp0kwFhosc9Rw14/7cpvax+1YQ=', max_length=128),
        ),
    ]
