# Generated by Django 5.1.1 on 2025-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0041_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$1auKzAiSQqSWeMBjszpLwv$3Y7ass8a7IymvEPA0hQ1dirC/V5zg4gSkm0yiiX4Qk4=', max_length=128),
        ),
    ]
