# Generated by Django 5.1.1 on 2025-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0042_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bfRauNH3JRliuaj9huBwBp$WaA5jJeMFtZjYpTyyV3VUXzQblX+sijjvQEgND6EpCo=', max_length=128),
        ),
    ]
