# Generated by Django 5.1.1 on 2025-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0043_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$HfLakCV8VIXgdWAYdYBRth$VHMXjZvv8u0quPRyv4TwyoZFEjdTTVGdnyvful4SxXs=', max_length=128),
        ),
    ]
