# Generated by Django 5.1.1 on 2025-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0044_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xhPW8aamUP9kowCcV53kro$dWmG/WMWXlKfENoxQaGHp0IsMfmwiUdabmIOpjW97fE=', max_length=128),
        ),
    ]
