# Generated by Django 5.1.1 on 2025-05-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0046_alter_detallecompra_id_compracorporativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_compraCorporativa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.compracorporativa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gJUowFMCfzv8KCOdzFjzNP$cSZGOSaFC1TurBIXIj/PS8baZKnjctDpp4RlJwp6BXM=', max_length=128),
        ),
    ]
