# Generated by Django 5.1.1 on 2025-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0047_alter_detallecompra_id_compracorporativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8oGwfgbxNzuioNfDxQzndS$qZo1E/kmValfFb7yjimvPYTzUIIYZttEgd/YPWHhe08=', max_length=128),
        ),
    ]
