# Generated by Django 5.1.1 on 2025-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0048_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$pCBeknR8dXr7GTP01clGo7$GJmFCbs05JeRXUDz4PZeChduZKhruSSOrIrMD9FXn08=', max_length=128),
        ),
    ]
