# Generated by Django 5.1.1 on 2025-05-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0050_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_compraCorporativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compracorporativa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$fxMvayHGTELrDUGdJlraTu$5Eka9+Z5HZuOhXGJ+JB34ZliUn6jkQ24ZyuINLcmgt0=', max_length=128),
        ),
    ]
