# Generated by Django 5.1.1 on 2025-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0051_alter_detallecompra_id_compracorporativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracorporativa',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RXQapprSQRDagVQxQUoHKq$IB5zJ4LKlq7v6unUQEVhW1GD3Lf6BkPPTZ6+++nIb5I=', max_length=128),
        ),
    ]
