# Generated by Django 5.1.1 on 2025-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0052_alter_compracorporativa_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='numeroDoc',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LsxayoOkeN3EoWZDXqUcXi$zZPU/GJdh1d8sQrojKGoNsDn8VvD03xlnn/66A4SKbg=', max_length=128),
        ),
    ]
