# Generated by Django 5.1.1 on 2025-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0053_detallecompra_numerodoc_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracorporativa',
            name='total_cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$mXdIg8yXjGmrkbMP0OYti4$8LBgE9RX1B3xeuBeTZ5FnTCDGHPyiVszL31COvi6erY=', max_length=128),
        ),
    ]
