# Generated by Django 5.1.1 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0054_compracorporativa_total_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$uSdbqYVdcY6uds31caJgUE$gwphJAKJtMHY2BwjL4UZURmrIQ1BA0j/9sAHQBUJVHw=', max_length=128),
        ),
    ]
