# Generated by Django 5.1.1 on 2025-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0055_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7yoZB9qOp8IW7PzmsrhIvn$ql1dwS3eqQhJL6NmqrCiCeKXB+5IFbxKKsM08O3J+FE=', max_length=128),
        ),
    ]
