# Generated by Django 5.1.1 on 2025-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0057_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$iaqbK6bJezRqtfsjuTybuT$p0s3FPPh/rAu7pFKwmANtq8TV7WJGIGm5OarEmCmTag=', max_length=128),
        ),
    ]
