# Generated by Django 5.1.1 on 2025-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0058_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$MnSFBhXwiK30R5ANMZcag2$SG8+BnBwq6qESQOyZncUP5S3aVx+YMbhIAkw6f0u1hY=', max_length=128),
        ),
    ]
