# Generated by Django 5.1.1 on 2025-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0059_alter_persona_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPayku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('url_pago', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$yMS23U4cgziA5S4PgNqZPE$mFZG++4430IhJUTWsUbrAiJU0YNlIE94pOlQf0CBJIM=', max_length=128),
        ),
    ]
