# Generated by Django 5.1.1 on 2025-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0060_transaccionpayku_alter_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total_Neto',
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ZAKerfe6OxPmOYOLmLQBmm$9r4IRzRa9bnphwBttLjsg3ll1nnG2MBeKTaZ7dbC73M=', max_length=128),
        ),
    ]
