# Generated by Django 5.1.1 on 2025-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0061_remove_factura_iva_remove_factura_total_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_Neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$zHBOcHyAM63IQcxQ8QsWhw$QXYHEm4zkce0aV04HDq6gUF7oyqub5w9/tCxE+XBKoY=', max_length=128),
        ),
    ]
