# Generated by Django 5.1.1 on 2025-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0062_factura_iva_factura_total_neto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='idMixCarga',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total_Neto',
        ),
        migrations.RemoveField(
            model_name='libroventas',
            name='total_Neto',
        ),
        migrations.RemoveField(
            model_name='libroventas',
            name='total_iva',
        ),
        migrations.RemoveField(
            model_name='notaventa',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='notaventa',
            name='totalNeto',
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RkCOwDBRgw69MHjVyRJ3bx$luDVj6sZGRsPLe8zLH/Laiane5SXxHFDp1oHiGX0x1A=', max_length=128),
        ),
    ]
