# Generated by Django 5.1.1 on 2025-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0063_remove_factura_idmixcarga_remove_factura_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='descuento',
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Vnho8OAXbbh52WrbfdmhWp$El8OpoNNuutgTyRpgSDg4ni5YJK9xRlkazU+0q5Npnk=', max_length=128),
        ),
    ]
