# Generated by Django 5.1.1 on 2025-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0064_remove_detallefactura_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$UUHx6MqsCFogdcKkyWmn3T$vf1vJE0dTyeuWhrHc2kDsb09Tr0Q10CEseBRJgNR+nM=', max_length=128),
        ),
    ]
