# Generated by Django 5.1.1 on 2025-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0065_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RnOYBJuFVf5JUsjIgckNx1$RyIA1KA0P2cyAUGgmyRJ3xddAZ0eeeY+wvqHqjaAodo=', max_length=128),
        ),
    ]
