# Generated by Django 5.1.1 on 2025-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0066_detallefactura_descuento_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YhmUHF0MXpKSjsxL2eKZnJ$hXqhIENNIuF/JWhrHcU/04rU8A8XWHVhFRbxR17BrtQ=', max_length=128),
        ),
    ]
