# Generated by Django 5.1.1 on 2025-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0067_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RrPSmffjILWhSaX687w7yS$+IDiutIJS7j+VarQhN4BhRMcaotGhJVtN02cwqZs10A=', max_length=128),
        ),
    ]
