# Generated by Django 5.1.1 on 2025-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0068_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$926ju4ktB5PHnkWRDR9z2b$AzKgud58MFV3VBkirVRXtwZnQJTlp+2/cKQcTpE5+aw=', max_length=128),
        ),
    ]
