# Generated by Django 5.1.1 on 2025-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0070_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JhRH20JkYBXw4l0imwkwAl$IwwZdY5lxqm/9QBlEbWJnKOwv7jHPojr40DeztEsAcY=', max_length=128),
        ),
    ]
