# Generated by Django 5.1.1 on 2025-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0071_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$L1wHlTq2QwZbzF7vfgpUBz$JREaQX0wmeqt89qBhG6L0NmI6gdaJGkRGWGZusbVu64=', max_length=128),
        ),
    ]
