# Generated by Django 5.1.1 on 2025-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0072_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$aA8FedLw0aqe7lI6ruPHjT$c+qtJZ+2f0iG8eAEInoc6HtBP203T+NUMQm6L+tx2Ts=', max_length=128),
        ),
    ]
