# Generated by Django 5.1.1 on 2025-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0073_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$1lznmQDl33yx80qAs6EU4D$v1K2Ys6KWQv261EnafJgIlnYtZrtWrBJzx+WD0Ag1RQ=', max_length=128),
        ),
    ]
