# Generated by Django 5.1.1 on 2025-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0074_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ZmLdkNbQy6Bfviwv7bkNME$MZswVpGjibS3LTuC324fNFn7RlbfQJYkLugkjT+pkAY=', max_length=128),
        ),
    ]
