# Generated by Django 5.1.1 on 2025-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0076_delete_transaccionpayku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8D3P7Q8wXqQ82CdZ4ht9sq$l0tBs8WggzgmZoAtW9G1VTTtkOJNdAsCDuzD+6AuvAA=', max_length=128),
        ),
    ]
