# Generated by Django 5.1.1 on 2025-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0077_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$HMReOObsTfx4Cy6HLJCsj9$Z8tFwZjeVmgkq10N0clV6w4LyjgVOb7gLWgb8frGods=', max_length=128),
        ),
    ]
