# Generated by Django 5.1.1 on 2025-05-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0078_persona_ciudad_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9pKCXKo8g1A2quEx9udX37$kMmiBdWKMZelMzgbdYOWJj8Y4HOplfuzDGDLUkyJSs0=', max_length=128),
        ),
    ]
