# Generated by Django 5.1.1 on 2025-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0079_alter_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$QRbry9U87J9ASkJH8PeFdx$WyubnmWnwPq7VqrsYDcczv603dd4vKL38HmCSeGyRT8=', max_length=128),
        ),
    ]
