# Generated by Django 5.1.1 on 2025-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0080_remove_persona_ciudad_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8dvgzPNK81M4ekj7mCYDfQ$iT/g6DdWLoidGVhxYfRMVsnPo+KPw0Gotyv7cGHPRfE=', max_length=128),
        ),
    ]
