# Generated by Django 5.1.1 on 2025-05-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0081_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$G1b0JaXyiEpSWYTqaf2aKL$UwqrvjoW20knEG1H0G4sY7g2w5vpQZyClHhQcjr6tLQ=', max_length=128),
        ),
    ]
