# Generated by Django 5.1.1 on 2025-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0082_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sWx9f2AkTvglc0nHkWKDQF$5VcVhmkWglDv5XSOS0mZwMhsOy758saZLnBwzU3ppW4=', max_length=128),
        ),
    ]
