# Generated by Django 5.1.1 on 2025-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0083_persona_ciudad_alter_persona_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='mapa_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ZOmDrbatHVMLGgJGoLLWrW$i9Hfncb7HbbRkV3FUGL2ljFT+ZDj/Ij1qtVSAaMT250=', max_length=128),
        ),
    ]
