# Generated by Django 5.1.1 on 2025-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0084_persona_mapa_url_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$VRQBRnmz8Cl5bnCl5x7TrE$ZpHk99Q0TYOd2muHK2m0MfTXBNtv1ezdIDAFNtFhy4Q=', max_length=128),
        ),
    ]
