# Generated by Django 5.1.1 on 2025-06-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0085_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$5NUt40drPccgqq4y7QpSyw$BLGM2/RqgAX7KUfXdKhLQT5aaMWJoUQHf5siRefjqRU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('ADMINISTRADOR', 'Administrador')], max_length=50),
        ),
    ]
