# Generated by Django 5.1.1 on 2025-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0086_alter_persona_password_alter_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sVl2cthY9nhLwZIMfCPtwJ$s2MdUNzStJ4bMOrqR3WXuN4kBq66ubjauPOi4wcrEmY=', max_length=128),
        ),
    ]
