# Generated by Django 5.1.1 on 2025-06-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0087_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hLbJXf8jaxQNmI2gv37Gpk$D0wexQttyuJ14QuTr2vjWkVzoOQ0qCfaS0al0YW5dGk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Administrador', 'Administrador')], max_length=50),
        ),
    ]
