# Generated by Django 5.1.1 on 2025-06-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0089_mensajecontacto_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$o3puiUOxxEqeAHwTu8MBLI$1yIy2KHhK0sfsoqw5HueLoDKa63yFxAXED5KDlSfPgQ=', max_length=128),
        ),
    ]
