# Generated by Django 5.1.1 on 2025-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0090_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$uBZVJ4TncvK9dHiJNMLeoi$rGxFmSSW1V/+JvtFLdzVpynv9epmIO6ErNKwX7pPWxE=', max_length=128),
        ),
    ]
