# Generated by Django 5.1.1 on 2025-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0091_alter_persona_direccion_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
