# Generated by Django 5.1.1 on 2025-06-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0093_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_ruta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.ruta'),
        ),
    ]
